#!/usr/bin/env python

"""
hoster instantiation
"""

try:
    import mangler
except ImportError:
    pass

import sys
import os
# extend module search path for access to tiddlywebconfig.py
cwd = os.getcwd()
sys.path.insert(0, cwd)

from tiddlywebplugins.hoster.config import config as init_config
from tiddlywebplugins.imaker import spawn
from tiddlywebplugins.hoster import instance


def main(args):
    args = [unicode(arg, "UTF-8") for arg in args]
    instance_path = args[1]
    spawn(instance_path, init_config, instance)
    return True


if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
